<?php

return [

    // General CP
    'dashboard' => 'ダッシュボード',
    'nav_dashboard' => 'ダッシュボード',
    'sneak_peek' => 'プレビュー',
    'sneak_peeking' => 'プレビュー',
    'view_site' => 'サイトを見る',
    'visit_url' => 'URLへ行く',
    'search_for_anything' => '何でもを検索する',

    // Pages
    'page' => 'ページ',
    'pages' => 'ページ',
    'nav_pages' => 'ページ',
    'create_page_button' => '新規ページ',
    'edit_homepage_button' => 'ホームページを編集',
    'create_page' => '新規ページ',
    'page_created' => 'ページが作成されました。',
    'editing_page' => 'ページを編集中',
    'page_updated' => 'ページが更新されました。',
    'home' => 'ホーム',
    'show_urls' => 'URLを表示させる',
    'show_titles' => 'タイトルを表示させる',
    'choose_page_type' => 'ページタイプを選択',
    'parent_page' => '親ページ',
    'pages_reordered' => 'ページが無事に再配置されました。',

    // Collections
    'collections' => 'コレクション',
    'nav_collections' => 'コレクション',
    'manage_collections' => 'コレクションを管理する',
    'create_collection_button' => '新規コレクション',
    'create_collection' => '新規コレクション',
    'collection_created' => ':title が作成されました。',
    'editing_collection' => ':collectionを編集中',
    'collection_updated' => ':title が更新されました。',
    'collections_empty' => 'コレクションとは、関連性があり、類似URLパターンを持つアイテムを含むコンテナです。',
    'collection_title_instructions' => 'あなたのコレクションのタイトル',
    'collection_handle_instructions' => "設定とテンプレートで使う変数名",
    'collection_order_instructions' => "このコレクションのデフォルトソートメソッドを設定する。",
    'collection_fieldset_instructions' => "このコレクションのデフォルトフィールドセット",
    'collection_template_instructions' => "このコレクションのデフォルトテンプレート",
    'collection_route_instructions' => "コレクションのルートは全アイテムのURLパターンを定義します。",
    'collection_does_not_exist' => 'コレクション :collection はありません。',

    // Entries
    'entry' => 'アイテム',
    'entries' => 'アイテム',
    'nav_entries' => 'アイテム',
    'create_entry_button' => '新規アイテム',
    'create_entry' => '新規 :noun',
    'entry_created' => 'アイテムが作成されました。',
    'editing_entry' => 'アイテムを編集中',
    'entry_updated' => 'アイテムが更新されました。',
    'entries_empty_見出し' => ':type アイテム',
    'entries_empty' => 'アイテムは自己URLとコンテンツがあり、よくブログ記事のようなリストで表示されます。',

    // Taxonomies
    'taxonomy' => 'タクソノミー',
    'taxonomies' => 'タクソノミー',
    'nav_taxonomies' => 'タクソノミー',
    'create_taxonomy' => '新規タクソノミー',
    'create_taxonomy_button' => '新規タクソノミー',
    'manage_taxonomies' => 'タクソノミーを管理',
    'editing_taxonomy' => 'タクソノミーを編集中',
    'taxonomy_updated' => 'タクソノミーが更新されました。',
    'taxonomy_created' => 'タクソノミーが作成されました。',
    'taxonomies_empty_見出し' => 'タクソノミー',
    'taxonomies_empty' => 'タクソノミーはデータを「カテゴリー」または「色」のようにユニークに「特徴分類するシステムです。',
    'taxonomies_title_instructions' => 'あなたのタクソノミーのタイトル',
    'taxonomies_slug_instructions' => '設定とテンプレートで使う名前',
    'taxonomies_fieldset_instructions' => 'このタクソノミーを編集中の時に表示するフィード。',
    'taxonomies_route_instructions' => 'このタクソノミーのタグはこのようなルートのパターンになります。',

    'taxonomy_terms' => 'タグ',
    'create_taxonomy_term_button' => '新規 :term',
    'create_taxonomy_term' => '新規 :term',
    'taxonomy_term_created' => 'タクソノミータグが作成されました。',
    'taxonomy_terms_empty_見出し' => ':term タグ',
    'taxonomy_terms_empty' => 'Where a Taxonomy is the grouping, a Term is the actual label applied to a piece of content. for {
    example, "Red" would be a term in "Colors".',

    // Globals
    'global' => 'グローバル',
    'globals' => 'グローバル',
    'nav_globals' => 'グローバル',
    'global_sets' => 'グローバルセット',
    'manage_global_sets' => 'グローバルセット管理',
    'configuring_global_set' => 'グローバルセットを設定中',
    'create_global_set_button' => '新規グローバル',
    'create_global_set' => '新規グローバル',
    'global_set_created' => ':type が作成されました。',
    'editing_globals' => 'グローバルを編集中',
    'globals_updated' => 'グローバルが更新されました。',
    'globals_empty_見出し' => 'グローバルセット',
    'globals_empty' => 'グローバルセットはURLに関係ないコンテンツの変数グループです。例えば：会社名、住所、連絡先、テンプレート設定。',
    'general_globals' => '一般',
    'globals_title_instructions' => "あなたのグローバルセットのタイトル。 例えば：フッターコンテンツまたはサイドバー設定。",
    'globals_slug_instructions' => "テンプレートで使う変数。例えば： <code>footer_content</code>または<code>sidebar_settings</code>.",
    'globals_fieldset_instructions' => "Pick which group of fields you want to use to manage this fieldset.",

    // Assets
    'assets' => 'アセット',
    'nav_assets' => 'アセット',
    'new_asset' => '新規アセット',
    'add_asset' => 'アセット追加',
    'browse_assets' => 'アセット閲覧',
    'browsing_assets' => 'アセットを閲覧中',
    'creating_asset' => 'アセットを作成中',
    'asset_created' => 'アセットが作成されました。',
    'editing_asset' => 'アセットを編集中',
    'asset_updated' => 'アセットが更新されました。',
    'drop_to_upload' => 'ドロップしてアップロード',
    'upload_asset' => 'アセットアップロード',
    'sync_assets' => 'アセット同期',
    'syncing_assets' => 'アセットを同期中',
    'new_folder' => '新規フォルダ',
    'upload' => 'アップロード',
    'uploads' => 'アップロード',
    'filename' => 'ファイル名',
    'filesize' => 'ファイルサイズ',
    'date_modified' => '更新日付',
    'parent_folder' => '親フォルダ',
    'containers' => 'コンテナ',
    'asset_folder_empty_見出し' => 'フォルダには何もありません。',
    'asset_folder_empty' => 'ファイルをアップロードするために、こちらへファイルをドラッグ&ドロップしてください。',
    'focal_point' => '焦点',
    'focal_point_label' => '焦点を調整するため、画像をクリックして下さい。',
    'focal_point_instructions' => 'The focal point is used when cropping so the most important part of the image is not removed.',
    'or_drag_and_drop_files' => 'ファイルをドラッグ&ドロップすることもできます。',
    'no_asset_container_specified' => 'No asset container specified.',
    'rename_file' => 'Rename File',
    'rename_file_warning' => 'Renaming a file will not update any references to it, which _may_ result in broken links in your site.',
    'move_file' => 'Move file',
    'move_file_warning' => 'Moving a file will not update any references to it, which _may_ result in broken links in your site.',
    'dimensions' => 'Dimensions',
    'last_modified' => 'Last Modified',
    'url_resolves_to' => 'URL resolves to: :path',


    // Folder
    'folder_title_instructions' => 'The display name of the folder.',
    'folder_directory_instructions' => 'The filesystem directory name',

    // Asset Containers
    'asset_containers' => 'Asset Container|Asset Containers',
    'manage_asset_containers' => 'Manage Asset Containers',
    'new_asset_container' => 'New Asset Container',
    'creating_asset_container' => 'Creating Asset Container',
    'asset_container_created' => 'Asset Container created',
    'editing_asset_container' => 'Editing Asset Container',
    'asset_container_updated' => 'Asset Container updated',
    'asset_containers_empty_見出し' => 'There are no configured asset containers.',
    'asset_containers_empty' => 'Each asset container can be a location on your file system, which can either be publicly accessible or protected from prying eyes.',
    'select_asset_container' => 'Select an asset container.',

    // Asset Folders
    'create_folder' => 'Create Folder',
    'edit_folder' => 'Edit Folder',
    'asset_name_instructions' => 'The display name of the container.',
    'asset_handle_instructions' => 'A unique string that you can use to reference your container. <b>This cannot be changed after creation.</b>',
    'asset_fieldset_instructions' => 'The fieldset to be used by assets in this container.',
    'asset_driver_instructions' => 'Where will the assets be stored and accessed?',
    'asset_path_instructions' => 'Location of the folder on the filesystem.',
    'asset_url_instructions' => 'URL of the folder.',
    'asset_folder_basename' => 'Folder name',

    // Fields Builder
    'add_field' => 'Add New Field',
    'quick_add' => 'Quick Add',
    'toggle_fields' => 'Toggle Fields',
    'sidebar' => 'Sidebar',
    'meta' => 'Meta',
    'all' => 'All',

    // Set Builder
    'add_set' => 'Add Set',
    'edit_set' => 'Edit Set',
    'delete_set' => 'Delete Set',
    'toggle_sets' => 'Toggle Sets',
    'set_fields_instructions' => "Choose this set's fields",

    // Amazon S3
    'access_key_id' => 'Access Key ID',
    'secret_access_key' => 'Secret Access Key',

    // Users
    'user' => 'User',
    'users' => 'User|Users',
    'nav_users' => 'Users',
    'manage_users' => 'Manage Users',
    'create_user_button' => 'Create User',
    'create_user' => 'Create User',
    'create_a_user' => 'Create a User',
    'user_created' => 'User created',
    'editing_user' => 'Editing User',
    'user_updated' => 'User updated',
    'reset_password' => 'Reset Your Password',
    'choose_new_password' => 'Choose a New Password',
    'new_password' => 'New Password',
    'change_password' => 'Change password',
    'send_email' => 'Send email',
    'email_sent' => 'Email sent',
    'send_activation_email' => 'Send activation email',
    'send_password_reset_email' => 'Send password reset email',
    'password_reset_email_not_sent' => 'Email not sent. Please check your logs.',
    'copy_activation_link' => 'Copy activation link',
    'copy_password_reset_link' => 'Copy password reset link',
    'copy_password_reset_link_failed' => 'There was a problem generating the link. Please check your logs.',
    'password_reset_sent' => 'Password reset email sent',
    'account_activated' => 'Your account has been activated',
    'password_reset_success' => 'You password has been reset',
    'activate_account' => 'Activate Account',
    'account' => 'アカウント',
    'password' => 'パスワード',
    'password_for' => ':username のパスワード',
    'my_account' => '私のアカウント',
    'profile' => 'プロフィール',
    'logout' => 'ログアウト',
    'sign_out' => 'ログアウト',
    'user_options' => 'ユーザー設定',
    'user_bio_instructions' => '自己紹介を書いてください。',
    'user_account_created' => 'A user account has been created.',
    'forgot_password' => 'パスワードを忘れましたか？',
    'invalid_user' => 'Invalid user',
    'invalid_code' => 'Invalid code',
    'invalid_creds' => 'Invalid credentials',
    'go_back' => '戻る',

    // Password Reset
    'reset_code_missing' => 'No code specified.',
    'reset_code_invalid' => 'Invalid code',

    // Roles
    'roles' => 'Role|Roles',
    'nav_user-roles' => 'User Roles',
    'create_role_button' => 'Create Role',
    'creating_role' => 'Create a Role',
    'role_created' => 'Role created',
    'editing_role' => 'Editing Role',
    'role_updated' => 'Role Updated',
    'roles_empty_見出し' => 'User Roles',
    'roles_empty' => 'User Roles allow you to group a number of permissions under a single label. For example, editor, publisher, and admin.',

    // Permissions
    'permissions' => 'Permission|Permissions',
    'access' => 'Access',
    'checking_folder_permissions' => 'Checking folder permissions, please wait...',
    'folders_permission_valid' => 'File and folder permissions look great!',
    'folders_unwritable' => 'The following directories need to be writable:',

    // Error Pages
    'error' => 'Error',
    'permission_denied' => 'ログインして下さい',
    'permission_denied_instructions' => "このページを見る権限がありません。",
    'page_not_found' => 'Page not found',
    'page_not_found_instructions' => 'The page you requested does not exist.',
    'session_expired' => 'Your session has expired.',
    'stache_building' => 'The cache is being updated. Please wait and try again.',
    'session_expired_error' => 'Your session has expired. Log in to continue where you left off.',
    'publish_error' => 'There was an issue saving your data. More detail can be found in your logs.',
    'error_fetching_data' => 'There was an issue fetching your data. More detail can be found in your logs.',

    // User Groups
    'usergroups' => 'User Group|User Groups',
    'user_groups' => 'User Groups',
    'nav_user-groups' => 'User Groups',
    'create_usergroup_button' => 'Create Group',
    'creating_usergroup' => 'Creating User Group',
    'usergroup_created' => 'User Group created',
    'editing_usergroup' => 'Editing User Group',
    'usergroup_updated' => 'User Group updated',
    'usergroups_empty_見出し' => 'User Groups',
    'usergroups_empty' => 'User Groups allow you mix and match different roles and users together into a single group.',

    // Settings
    'settings' => 'Setting|Settings',
    'nav_settings' => 'Settings',
    'settings_cp' => 'Control Panel',
    'settings_routes' => 'Routes',
    'settings_search' => 'Search',
    'settings_system' => 'System',
    'settings_assets' => 'Assets',
    'settings_caching' => 'Caching',
    'settings_debug' => 'Debugging',
    'settings_email' => 'Email',
    'settings_theming' => 'Theming',
    'settings_users' => 'Users',
    'settings_updated' => 'Settings saved.',
    'settings_updated_and_indexed' => 'Settings saved and search indexes updated.',
    'settings_locales_instructions' => "Create a locale for each language translation. You can skip this for now and do it later if you'd prefer.",
    'settings_locales_index_php_warning' => "You will need to change the <code>\$locale</code> to <code>:locale</code> in your <code>index.php</code> file.",
    'settings_debug_mode_instructions' => "Enabling Debug Mode will display all errors on screen. It's a great tool while a site is development, but remember to disable it in production.",

    'shorthand' => 'Shorthand',
    'shorthand_instructions' => 'The 2 character language code.<br> Example: `en`, `de`.',
    'add_locale' => 'Add Locale',
    'full_locale' => 'Full Locale',
    'full_locale_instructions' => 'Used for PHP date localization.<br>Example: `en_US`, `de_DE`.',
    'locale_name_instructions' => 'Used for display.<br> Example: `English`, `German`.',
    'locale_url_instructions' => 'Example: `http://example.com/de/`',



    // Addons
    'addons' => 'Addon|Addons',
    'manage_addons' => 'Manage Addons',
    'nav_addons' => 'Addons',
    'addons_empty_見出し' => 'There are no addons',
    'addons_empty' => 'Addons extend the functionality of Statamic.',

    // Fieldsets & Fields
    'fieldset' => 'Fieldset',
    'fieldsets' => 'Fieldset|Fieldsets',
    'nav_fieldsets' => 'Fieldsets',
    'create_fieldset_button' => 'Create Fieldset',
    'create_fieldset' => 'Create a Fieldset',
    'fieldset_created' => 'Fieldset created',
    'editing_fieldset' => 'Editing Fieldset',
    'fieldset_updated' => 'Fieldset updated',
    'fieldsets_empty' => 'Fieldsets let you create and manage reusable groups of fieldtypes that in turn manage your content. This is where content modeling happens.',
    'fieldset_title_instructions' => 'Display Name, usually a singular noun.',
    'fieldset_handle_instructions' => "Used in settings/templates.",
    'fieldset_create_title_instructions' => "Optional, shown when creating new content",
    'fieldset_hide_instructions' => "Hide from selection dialogs?",
    'fieldset_fields_instructions' => 'Assign and customize the fields and fieldtypes in this fieldset.',
    'fieldset_taxonomies_instructions' => 'Show, hide, and configure the taxonomies that should be displayed in this fieldset.',
    'create_title' => '新規タイトル',
    'display_name' => "Display Name",
    'display_name_instructions' => "The field's label shown in the Control Panel.",
    'display_text' => 'Display Text',
    'display_text_instructions' => "項目ラベル",
    'field_name' => '項目名',
    'field_name_instructions' => '綱目変数',
    'field_required' => '必須',
    'field_required_instructions' => 'この項目は必須です。',
    'field_variable' => "項目変数",
    'field_variable_instructions' => "The field's template variable.",
    'field_instructions_instructions' => "基本的なMarkdownを使うことができます。使ってみてください。",
    'field_width_instructions' => 'The size of the field in the fieldset layout.',
    'validation_rules' => "Validation Rules",
    'validation_instructions' => "Has access to all of Laravel's",
    'validation_instructions_link_text' => 'validation rules',
    'validation_rules_instructions' => 'Enter a pipe delimited string of <a href=":url" target="_blank">validation rules</a>.',
    'default_value' => 'Default Value',
    'field_default_value_instructions' => 'Enter the default value for string-type fields.',
    'edit_field' => 'Edit Field',
    'choose_field_to_edit' => "Choose a field to edit its settings.",
    'select_fieldtype' => 'Select Fieldtype',
    'field_added' => ":fieldtype field added.",
    'set_added' => "Set added.",
    'append_taxonomies' => 'Append Taxonomies on Entries',
    'append_taxonomies_instructions' => "When using this fieldset on an entry, any taxonomies not defined in the fieldset will be automatically added to the sidebar.",
    'type_url' => 'Type a URL',
    'type_url_or_search' => 'Type a URL or search for an item',

    'sections' => 'セクション',
    'section_label' => "セクションラベル",
    'section_handle' => "セクションハンドル",
    'section_handle_tip' => "Tip: You can name your section 'sidebar' to transform it into one.",
    'sections_and_fields' => "セクションと項目",

    'display_conditions' => 'Display Conditions',
    'display_conditions_instructions' => 'Configure when this field will be shown.',
    'always_show' => '常に表示する',
    'show_when' => 'Show when...',
    'hide_when' => 'Hide when...',
    'standard' => 'スタンダード',
    'custom' => 'カスタム',
    'display_standard_instructions' => 'Choose a combination of fields and corresponding values.',
    'display_custom_instructions' => 'Enter your custom JavaScript condition method name.',

    'basics' => '基本',
    'visibility' => 'Visibility',
    'extras' => 'ボーナス',

    'fieldtype_category_text' => 'テキスト',
    'fieldtype_category_media' => 'メディア',
    'fieldtype_category_pickable' => 'Pickable',
    'fieldtype_category_structured' => 'Structured',
    'fieldtype_category_relationship' => 'リレーション',
    'fieldtype_category_special' => 'スペシャル',
    'fieldtype_category_system' => 'システム',

    // Forms
    'form' => 'フォーム',
    'forms' => 'フォーム',
    'nav_forms' => 'フォーム',
    'forms_empty' => 'Forms collect, display, and report user submitted responses.',
    'create_form' => '新規フォーム',
    'form_updated' => 'Form updated',
    'form_created' => 'Form created',
    'form_submission_deleted' => 'Submission deleted.',
    'submissions' => 'Submission|Submissions',
    'response' => 'response|responses',
    'empty_responses' => 'This form is awaiting responses.',
    'create_formset' => 'Create Formset',
    'creating_formset' => 'Creating Formset',
    'editing_formset' => 'Editing Formset',
    'import' => 'Import',
    'import_data' => 'Import Data',
    'import_link_text' => 'Learn about the import JSON format',
    'export' => 'Export',
    'export_csv' => 'Export as CSV',
    'export_json' => 'Export as JSON',

    // Formset Builder
    'formset_title_instructions' => "Your formset's proper label.",
    'formset_slug_instructions' => 'How the formset will be referenced.',
    'formset_metrics_instructions' => 'Specify any metrics you would like displayed.',
    'formset_metrics_grid_add_row' => 'Metric',
    'formset_metrics_grid_type_field' => 'Metric Type',
    'formset_metrics_grid_type_option_sum' => 'Sum',
    'formset_metrics_grid_type_option_total' => 'Total',
    'formset_metrics_grid_type_option_average' => 'Average',
    'formset_metrics_grid_label_field' => 'Label',
    'formset_metrics_grid_params_field' => 'Parameters',
    'formset_emails_instructions' => 'Add any emails you want to be sent upon submission.',
    'formset_emails_grid_add_row' => 'Email',
    'formset_emails_grid_to_field' => 'Recipient (To)',
    'formset_emails_grid_to_instructions' => 'Email address of the recipient.',
    'formset_emails_grid_from_field' => 'Sender (From)',
    'formset_emails_grid_from_instructions' => 'Leave blank to fall back to the site default.',
    'formset_emails_grid_reply_to_field' => 'Reply to',
    'formset_emails_grid_subject_field' => 'Subject',
    'formset_emails_grid_subject_instructions' => 'Email subject line.',
    'formset_emails_grid_template_field' => 'Template',
    'formset_emails_grid_template_instructions' => 'Leave blank to use an automagic email.',
    'formset_honeypot_field' => 'Honeypot Field',
    'formset_honeypot_instructions' => 'The field name to be used for the honeypot.',
    'formset_store_field' => 'Store Submissions',
    'formset_store_instructions' => 'Whether form submissions should be stored. Useful if you only wish to get email notifications.',
    'formset_honeypot_link' => "What's a honeypot?",
    'formset_fields_instructions' => 'Choose and customize the fields in this form.',

    // Updater
    'nav_updater' => 'Updater',
    'updates'     => 'Updates',
    'system_updates' => 'System Updates',
    'upgrade_to_latest' => 'Upgrade to Latest',
    'upgrade_to_version' => 'Upgrade to :version',
    'downgrade_to_version' => 'Downgrade to :version',
    'update_available' => 'Update Available',
    'update_complete' => 'Update complete.',
    'up_to_date' => 'Up to date!',
    'on_latest' => 'You are running the latest version of Statamic',
    'current_version' => 'Current Version',
    'released_on_date' => 'Released on :date',
    'updates_available' => 'There is an update available|There are :updates updates available',
    'backup_failed' => 'Backup Failed',
    'backup' => 'Backup',
    'backed_up' => 'Backed up',
    'backing_up' => 'Backing up...',
    'backing_up_instructions' => "We're zipping up your <code>statamic</code> folder, just in case you need to roll back.",
    'backup_reminder' => 'This is a safe process. We back up everything during running the update so you can always find your most recent version in <code>local/temp</code> if something goes wrong.',
    'couldnt_fetch_updates' => 'There was a problem fetching updates',

    // Download
    'downloading' => 'Downloading...',
    'downloaded' => 'Downloaded.',
    'download_failed' => 'Download Failed',
    'downloading_latest' => 'Getting the latest and greatest version of Statamic for you.',
    'downloading_version' => 'Getting v:version',

    // Installation
    'installation' => 'Installation',
    'installation_has_failed' => 'Installation has failed',
    'preparing_installation' => 'Installation will begin once the backup and download have completed.',
    'now_running' => "You're now running Statamic v:version",
    'statamic_ready' => 'Statamic is ready and waiting for you.',
    'delete_installer' => 'Please delete the <code>installer.php</code> file.',
    'installer_deleted' => 'I deleted it. Take me to the Control Panel &rarr;',

    // Archive
    'unzipping_files' => 'Unzipping files...',
    'unzipping_files_instructions' => 'Placing the files from the Statamic zip in a temporary location.',
    'unzipped_files' => 'Files unzipped.',

    // Dependencies
    'installing_dependencies' => 'Installing Dependencies...',
    'installing_dependencies_instructions' => 'Any addons with dependencies will need to be fetched. This may take a moment.',
    'dependencies_installed' => 'Dependencies installed.',

    // Swap Release
    'swapping_files' => 'Swapping files...',
    'swapping_files_instructions' => 'Statamic is being injected with software growth hormone (SGH). Results will be visible in mere moments.',
    'files_swapped' => 'Files swapped.',

    // Clean Up
    'cleaning_up' => 'Cleaning up...',
    'cleaning_up_instructions' => "We're deleting the temporary files created during the update.",

    // Importers
    'nav_import' => 'Import',
    'site_url' => 'Site URL',
    'import_from_version' => 'Import content from Statamic :version',
    'import_complete' => 'Import Complete',
    'import_has_completed' => 'The import has completed.',
    'import_summary' => 'Import Summary',
    'import_site_url_instructions' => 'Enter the URL of the existing website you will be importing.',

    'duplicate_item_warning'  => "There's one duplicate.|There are :count duplicates.",
    'uncheck_duplicates' => 'Uncheck Duplicates',

    'from_json' => 'From JSON',
    'json_file' => 'JSON File',
    'upload_json_file' => 'Upload a JSON file',

    // Export
    'export_failed' => 'Exporting Failed',
    'export_export_failed_with_error' => 'Export faileed with error:',

    'manage_widgets' => 'Manage Widgets',

    // Things
    'thing_created' => ':thing created.',
    'thing_updated' => ':thing updated.',
    'thing_deleted' => ':thing deleted.',
    'thing_configure' => 'Configure :thing',
    'thing_saved' => ':thing saved.',
    'thing_editing' => 'Editing :thing',

    'saved_success' => 'Saved',

    // Statuses
    'statuses' => 'ステータス',
    'status_pending' => '処理中',
    'status_active' => 'Active',
    'published' => '公開中',

    // Shortcuts
    'keyboard_shortcuts' => 'Keyboard Shortcuts',
    'show_keyboard_shortcuts' => 'Show Keyboard Shortcuts',

    // License
    'license_keys' => 'ライセンス',
    'trial_mode' => 'トライアルモード',
    'trial_mode_missing_license_keys' => '公開する前に、ライセンスが必要です。',
    'trial_mode_invalid_license_keys' => 'You have entered invalid license keys.',
    'trial_mode_license_keys_for_domains' => 'Valid license keys entered for :domains',
    'invalid_license_keys' => 'Please purchase and enter your license key or risk violating the License Agreement.',
    'license_keys_incorrect_domain' => 'License keys entered for incorrect domain. Please remedy or risk violating the License Agreement.',
    'checking_license_key' => 'Checking your license key, please wait...',
    'license_missing' => 'ライセンスが登録されていません。',
    'license_valid' => '有効なライセンスが登録されています。',
    'license_invalid' => 'このライセンスは無効です。',
    'license_wrong_domain' => 'このライセンスは :domain に繋がっています。',
    'license_no_domain' => 'このライセンスはまだドメインに繋がっていません。',
    'license_key_instructions' => 'あなたのライセンスを入力して下さい。<a href=":licenses">Statamic アカウント</a>で確認できます。必要であれば、<a href=":buy_license">新しいライセンスを注文できます。</a>。',
    'buy_now' => '注文',
    'license_statamic_link' => 'statamic.comでライセンスを注文して、ドメインを管理します。',

    'continue_in_trial_mode' => 'Continue in Trial Mode',
    'unlicensed' => 'Unlicensed',
    'unlicensed_message' => 'Please purchase and enter your license key or risk violating the License Agreement.',
    'on_trial_with_invalid_license' => 'You are currently on trial mode, but your license is invalid.',
    'on_trial_without_license' => 'You are currently on trial mode. Remember to add a license key before you move to a public domain.',
    'invalid_statamic_license' => 'Your Statamic license is invalid.',
    'couldnt_connect_to_outpost' => 'There was a problem communicating with the Statamic Outpost.',

    // Verbs and helpers
    'actions' => 'アクション',
    'add' => '追加',
    'edit' => '編集',
    'editing' => '編集中',
    'view' => '見る',
    'remove' => '削除',
    'update' => '更新',
    'delete' => '削除',
    'uncheck_all' => '全てのチェックを外す',
    'duplicate' => '複製',
    'manage' => '管理',
    'create' => '作成',
    'reorder' => 'ソート',
    'submit' => '提出',
    'save' => '保存',
    'saving' => '保存中',
    'save_changes' => '保存',
    'save_and_continue' => '保存して続ける',
    'save_and_another' => '保存してもう一個作成する',
    'are_you_sure' => 'よろしいですか？',
    'yes_im_sure' => 'はい、大丈夫です。',
    'refresh' => '更新',
    'cancel' => 'キャンセル',
    'loading' => '読み込み中',
    'expand' => 'Expand',
    'collapse' => 'Collapse',
    'show' => '表示',
    'hide' => '非表示',
    'move' => '移動',
    'edit_layout' => 'Edit Layout',
    'save_layout' => 'Save Layout',
    'save_order' => '順位保存',
    'toggle_dropdown' => 'Toggle Dropdown',
    'Confirm_delete_items' => 'This item will be deleted|The selected items will be deleted',
    'confirm_delete_page' => ' will be deleted along with all its children',
    'confirm_delete_folder' => 'This folder will be deleted',
    'configure' => 'Configure',
    'browse' => '閲覧',
    'select' => '選択',
    'localizing' => 'Localizing',
    'add_row' => 'Add Row',
    'localizable' => 'Localizable',
    'please_wait' => 'Please Wait...',
    'exporting' => 'Exporting...',
    'importing' => 'Importing...',
    'return_to_dashboard' => 'ダッシュボードへ戻る',
    'publish_content' => 'コンテンツ公開',
    'close_this_window' => 'このウィンドウを閉める',
    'toggle_navigation' => 'Toggle navigation',
    'logging_in' => 'ログイン中...',
    'logged_in' => 'ログインできました。',
    'logged_in_taking_you_to_cp' => 'ログインできました！ダッシュボードへ行きます...',
    'write' => '書く',
    'preview' => 'プレビュー',
    'collapse_all' => 'Collapse All',
    'expand_all' => 'Expand All',
    'please_select' => 'Please select',
    'selected' => 'selected',
    'add_another_item' => 'Add another item',
    'show_drafts' => '下書き表示',
    'hide_drafts' => '下書き非表示',
    'count' => 'カウント',
    'reset' => 'リセット',
    'installed' => 'Installed',
    'add_condition' => 'Add Condition',
    'open' => '開く',
    'download' => 'ダウンロード',
    'locale' => '地域',
    'hidden' => 'Hidden',

    // Nouns and whatnot
    'fields' => 'フィールド',
    'locales' => '地域',
    'keys' => 'キー',
    'values' => 'バリュー',
    'names' => '名前',
    'usernames' => 'ユーザーネーム',
    'emails' => 'メール',
    'passwords' => 'パスワード',
    'confirm_password' => 'パスワード確認',
    'remember_me' => '私を覚えて下さい',
    'title' => 'タイトル',
    'titles' => 'タイトル',
    'slug' => 'スラグ',
    'slugs' => 'スラグ',
    'rows' => 'Row|Rows',
    'columns' => 'Column|Columns',
    'folders' => 'フォルダ',
    'date' => '日付',
    'dates' => '日付',
    'date_and_time' => '日付と時間',
    'datestring' => '日付',
    'publish_date' => 'パブリッシュの日付',
    'items' => 'アイテム',
    'add_date' => '日付追加',
    'add_time' => '時間追加',
    'login' => 'ログイン',
    'login_with' => ':provider とログイン',
    'login_to_continue' => "ログインして続ける",
    'new' => '新規',
    'or' => 'または',
    'order' => '順位',
    'one_quarter' => '1/4 - One quarter',
    'three_quarters' => '3/4 - Three quarters',
    'one_third' => '1/3 - One third',
    'two_thirds' => '2/3 - Two thirds',
    'half' => 'Half',
    'full_width' => 'Full width',
    'width' => 'Width',
    'version' => 'バージョン',
    'versions' => 'バージョン',
    'developer' => '開発者',
    'developers' => '開発者',
    'developer_mode' => '開発モード',
    'description' => 'Description',
    'descriptions' => 'Description|Descriptions',
    'name' => '名前',
    'username' => 'ユーザーネーム',
    'email' => 'メール',
    'done' => '完了',
    'close' => '閉める',
    'templates' => 'テンプレート',
    'authors' => 'Author|Authors',
    'installer' => 'インストーラー',
    'search' => '検索',
    'search_results' => '検索結果',
    'no_search_results' => '検索結果はありません。',
    'instructions' => 'Instructions',
    'handle' => 'Handle',
    'label' => 'Label',
    'type' => 'タイプ',
    'route' => 'ルート',
    'terms' => 'Term|Terms',
    'progress' => 'Progress',
    'variables' => 'Variable|Variables',
    'license_key' => 'ライセンスキー',
    'driver' => 'ドライバー',
    'path' => 'パス',
    'url' => 'URL',
    'valid_url' => '有効URL',
    'invalid_url' => '無効URL',
    'bucket' => 'バケツ',
    'region' => '地域',
    'metrics' => 'Metric|Metrics',
    'whats_this' => "これは何ですか？",
    'first_name' => '下名前',
    'last_name' => '名字',
    'bio' => '自己紹介',
    'markdown_cheatsheet' => 'Markdownの使い方',
    'locales_and_urls' => 'Locales and URLs',
    'debug_mode' => 'デバッグモード',
    'defined_in_environment' => 'Managed externally by your environment.',
    'be_right_back' => '少々お待ちください。',
    'size' => 'サイズ',
    'read_only' => "Read Only",
    'read_only_mode' => "Read Only Mode",
    'next_step' => "Next Step",
    'invalid_creds' => 'These credentials are incorrect',

    'nav_content' => 'コンテンツ',
    'nav_tools' => 'ツール',
    'nav_configure' => '定義',
    'nav_addons' => 'アドオン',
    'nav_fieldsets' => 'フィールドセット',
    'nav_settings' => '設定',
    'nav_users' => 'ユーザー',
    'nav_resolve_duplicate_ids' => 'Duplicate IDs',

    'mount_collection' => 'マウントコレクション',
    'unmount_collection' => 'アンマウントコレクション',

    // Validation
    'handle_exists' => 'A container with this handle already exists.',

    // Duplicate ID Manager
    'duplicate_id_title' => 'Duplicate IDs',
    'no_duplicate_ids' => 'No duplicate IDs detected.',
    'generate_new_id' => 'Generate new ID.',

    // Path
    'path_resolves_to'    => 'Path resolves to: :path',
    'path_exists'         => 'Path exists.',
    'path_does_not_exist' => 'Path does not exist.',

    // Bard
    '見出し_1'          => '見出し 1',
    '見出し_2'          => '見出し 2',
    '見出し_3'          => '見出し 3',
    '見出し_4'          => '見出し 4',
    '見出し_5'          => '見出し 5',
    '見出し_6'          => '見出し 6',
    'bold'               => 'ボルド',
    'italic'             => 'イタリック',
    'underline'          => '下線',
    'strikethrough'      => 'Strikethrough',
    'remove_formatting'  => 'Remove Formatting',
    'unordered_list'     => 'Unordered List',
    'ordered_list'       => 'Ordered List',
    'blockquote'         => 'Blockquote',
    'superscript'        => 'Superscript',
    'subscript'          => 'Subscript',
    'add_link'           => 'リンク追加',
    'remove_link'        => 'リンク削除',
    'link_to_asset'      => 'アセットにリンク',
    'inline_code'        => 'Inline Code',
    'edit_link'          => 'リンク編集',
    'open_in_new_window' => '新規ウィンドウで開く',
];
